### ISSUE TITLE
Lightning Talk Presentation Slides

### ISSUE THREAD

**Issue by nguynam** [Keindae/HeatMapSimulationApp#37]

**Comment by Keindae** [comment]
Mon 11 Dec - Each team will get 3-4 slides for the lightning talks (see guidelines below). They are due to your instructor in PPT format. PLEASE USE 4:3 ASPECT RATIO SO THINGS LOOK FINE ON THE PROJECTOR. If your project was sponsored, be sure to mention and thank your sponsor for their participation in the course.
